### ISSUE TITLE
README links are dead

### ISSUE THREAD

**Issue by schiltz3** [Antares-Network/AntaresBot#159]
**Describe the bug**
Bot feature links are broken in README

**To Reproduce**
Go to repo [AntaresBot](https://github.com/Antares-Network/AntaresBot)
Click on [Bot Features](https://github.com/Antares-Network/AntaresBot) links

**Expected behavior**
Links should bring you somewhere :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/45466247/188337119-9dc29afd-db36-416e-8513-048e3076afd5.png)

 - Browser: chrome (Brave)

**Comment by nathen418** [comment]
readme links just got deleted :P to be added again with a new system sometime
